name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  cdp-workflows:
    uses: defra-cdp-sandpit/cdp-workflows/.github/workflows/node-check-pull-request.yml@main
