name: Publish

on:
  push:
    branches:
      - main
env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: '094954420758'

jobs:
  build:
    name: CDP-build-workflow
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build and Publish
        uses: DEFRA/cdp-build-action/build@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
